import {loadTimeData} from './resources/load_time_data.js';
loadTimeData.data = {
    "bestScore": "Лучшее достижение: $1$2$3",
    "bestScoreFlyout": "Лучший результат: $1",
    "bestScoreMenuDisplay": "$1$2",
    "cancel": "Отмена",
    "close": "Закрыть",
    "code": "Активирован чит-код!",
    "codeCheat": "Активирован чит-код! $1",
    "codeScoring": "Получение баллов отключено в этом раунде.",
    "congrats": "Вы обыграли $1% глобальных игроков!",
    "endlessBestScore": 1894,
    "endlessDescriptor": "расстояние",
    "endlessModeTitleInline": "Бесконечный:",
    "endlessTitle": "Бесконечный",
    "endlessUnit": "м",
    "fontfamily": "system-ui, sans-serif",
    "fontfamilyMd": "system-ui, sans-serif",
    "fontsize": "75%",
    "gameCreditsButton": "Титры игры",
    "gameCreditsDialogTitle": "Титры игры",
    "gameMode": "Режим игры изменен на \"$1\"",
    "gameModeSelectLabel": "Режим игры",
    "gameModeSelectLabelDisabled": "Режим игры (чтобы изменить его, начните новую игру)",
    "gameSettings": "Настройки игры",
    "highVisibilityActive": false,
    "highVisiblityModeToggleLabel": "Высокая видимость",
    "howToPlayButton": "Как играть",
    "howToPlayControllerBoost": "Чтобы воспользоваться увеличением скорости, нажмите правый триггер",
    "howToPlayControllerMovement": "Чтобы применять рулевое управление, используйте аналоговый стик или крестовину",
    "howToPlayControllerRefresh": "Чтобы перезапустить игру, одновременно нажмите левый и правый бамперы",
    "howToPlayDialogTitle": "Как играть",
    "howToPlayEndless": "Доберитесь как можно дальше и спасите друга от врагов",
    "howToPlayKeyboardBoost": "Чтобы воспользоваться увеличением скорости, нажмите клавишу F",
    "howToPlayKeyboardMovement": "Чтобы применять рулевое управление, используйте клавиши со стрелками или клавиши W, A, S, D",
    "howToPlayKeyboardRefresh": "Чтобы перезапустить игру, обновите страницу",
    "howToPlayMouseBoost": "Чтобы воспользоваться увеличением скорости, щелкните правой кнопкой мыши",
    "howToPlayMouseMovement": "Чтоб использовать рулевое управление, двигайте мышью",
    "howToPlayMouseRefresh": "Чтобы перезапустить игру, обновите страницу",
    "howToPlayTimeTrial": "Доберитесь до конца как можно быстрее и собирайте монеты, чтобы сократить время",
    "howToPlayTouchBoost": "Проведите пальцем вниз дважды, чтобы увеличить скорость",
    "howToPlayTouchMovement": "Проведите пальцем или коснитесь, чтобы использовать рулевое управление",
    "howToPlayTouchRefresh": "Чтобы перезапустить игру, обновите страницу",
    "howToPlayZigZag": "Пройдите через максимальное количество шлюзов подряд",
    "isDebugMode": false,
    "isLinuxTuxEnabled": true,
    "isNewShare": true,
    "is_windows_xbox_sku": "false",
    "keyboardAction": "пробел",
    "language": "ru",
    "lastSelectedMode": "endless",
    "lastSelectedPlayer": 8,
    "lastSelectedTheme": "surf",
    "menuInfo": "для начала игры",
    "mouseAction": "двойной щелчок",
    "newBestScore": "Новое лучшее достижение: $1$2$3",
    "newGame": "Начать новую игру",
    "off": "Отключено",
    "on": "Включено",
    "overInfo": "для повторной игры",
    "overTitle": "Хорошая попытка!",
    "pauseInfo": "для продолжения игры",
    "pauseTitle": "Игра приостановлена",
    "reducedSpeedActive": false,
    "reducedSpeedModeToggleLabel": "Пониженная скорость",
    "resetAllStats": "Сбросить всю статистику",
    "resetAllStatsDialogText": "Вы действительно хотите сбросить всю статистику игры, в том числе рекорды?",
    "resetAllStatsDialogTitle": "Сбросить всю статистику",
    "share": "Поделиться с другом",
    "shareButtonString": "Поделиться",
    "shareCopy": "Копировать",
    "shareLinkCopied": "Скопировано",
    "shareLinkFlyout": "https://go.microsoft.com/fwlink/?linkid=2162539",
    "shareLinkGameOver": "https://go.microsoft.com/fwlink/?linkid=2168605",
    "shareNewLinkMobile": "https://microsoftedgewelcome.microsoft.com/emmx/edge-surf",
    "shareString": "Мне попалась супер веселая игра, давайте заниматься серфингом вместе!",
    "skiTheme": "Покатаемся на лыжах",
    "specialThanks": "Особая благодарность:",
    "startShare": "Запустить общий доступ",
    "surfTheme": "Давайте займемся серфингом",
    "textdirection": "ltr",
    "theme": "Тема изменена на $1",
    "themeSelectLabel": "Тема",
    "timetrialBestScore": -1,
    "timetrialDescriptor": "время",
    "timetrialModeTitleInline": "Испытание на время:",
    "timetrialTitle": "Испытание на время",
    "timetrialUnit": "с",
    "touchAction": "двойное касание",
    "zigzagBestScore": -1,
    "zigzagDescriptor": "серия",
    "zigzagModeTitleInline": "Зигзаг:",
    "zigzagTitle": "Зигзаг",
    "zigzagUnit": "шлюзы"
};
